CREATE TABLE PERSON
(
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PERSON PRIMARY KEY(ID),
    CONSTRAINT UNQ_EMAIL_PERSON UNIQUE(EMAIL)
);

CREATE TABLE PHYSICALPERSON
(
    ID INTEGER NOT NULL,
    PERSON_ID INTEGER NOT NULL,
    SALARY DECIMAL(12,2) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    GENDER CHAR(1) NOT NULL,
    CONSTRAINT PK_PHYSICALPERSON PRIMARY KEY(ID),
    CONSTRAINT FK_PHYSICALPERSON_PERSON FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID),
 	CONSTRAINT CHK_SALARY_CUSTOMER CHECK(SALARY >= 0),
 	CONSTRAINT CHK_BIRTHDAY_CUSTOMER CHECK(BIRTHDAY <= date('now','-18 year')),
    CONSTRAINT CHK_GENDER_CUSTOMER CHECK(GENDER = 'M' OR GENDER = 'F')
);